### PR TITLE
Image optimisation

### PR DESCRIPTION
**Pull request by michaelcarter**

### CODE REVIEW

**Comment by chrisannetts** [comment]
In general, I'm happy to go with this approach. But have a few bits of feedback that I'd like to address first.

First of all, there are two examples where the conversion has had a more-than-acceptable (in my opinion) impact on the image quality:

Screenshot 2020-04-29 at 18 12 44
Screenshot 2020-04-29 at 18 12 26

Second of all, I'm seeing JPEGs in Chrome, which supports WebP. Would it make sense to serve modern image formats to modern browsers, and use these optimisations where we have to fall back to PNGs?

Finally, another consideration is that the new case studies will _need_ to be transparent; the background colour will change depending on your scroll offset, so the images within the page need to accommodate  the viable background. Is there a way we can ignore this optimisation on particular folders or pages?

**Comment by michaelcarter** [comment]
@chrisannetts 

> First of all, there are two examples where the conversion has had a more-than-acceptable (in my opinion) impact on the image quality

Could you let me know specifically what aspects of the compression aren't to your liking and I'll see what I can do to tweak? We have a fair amount of control over how the images are compressed, and so room to optimise.

> Second of all, I'm seeing JPEGs in Chrome, which supports WebP. Would it make sense to serve modern image formats to modern browsers, and use these optimisations where we have to fall back to PNGs?

Making a bit of an assumption here, so please correct me if it's wrong, but are you looking at the filenames to determine this? If so, you need to look at the content type in web inspector:

Screenshot 2020-04-30 at 13 50 53

Cloudflare's [polish feature](https://support.cloudflare.com/hc/en-us/articles/360000607372-Using-Cloudflare-Polish-to-compress-images) will make a decision when the image is requested about what content type to use based on the browser making the request and the compressibility of the image itself. It passes along information on the compression made in response headers on the asset.

> Finally, another consideration is that the new case studies will need to be transparent.

This is fine, the script doesn't remove the original pngs, just leaves a jpg there in the same directory should we decide to use it.

**Comment by chrisannetts** [comment]
Awesome. I was indeed looking in the Inspector at the file names rather than the file types.

On the two images, it's the shadows in both cases. They should be smooth, but both are causing visible 'rings'.

**Comment by michaelcarter** [comment]
@chrisannetts - I've had a play with the image compression settings, switching it out for a different algorithm. Using the new settings, the jpg has increased in size by 22KB, but the banding effect is much improved upon. See the examples below:

Current (106KB - old)
presentation-original

Updated settings (128KB - updated with less obvious banding)
presentation

For reference, the original png was 1.1MB, so even with the extra 22KB, there's a 8.8x improvement here on file size. 

Let me know if you're happy for me to get this deployed.

**Pull request merged**
